version: 2.1

workflows:
  ci:
    jobs:
      - test-job

jobs:
  test-job:
    machine: true
    resource_class: my-namespace/my-rc
    steps:
      - run: echo "hello world11"
      - store_artifacts:
          path: newfile.txt
          destination: docs

